# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/main_design/main_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_dvdr_0_0/main_design_clk_dvdr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_clk_dvdr_0_0 || ORIG_REF_NAME==main_design_clk_dvdr_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_dvdr_1_0/main_design_clk_dvdr_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_clk_dvdr_1_0 || ORIG_REF_NAME==main_design_clk_dvdr_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_dvdr_2_0/main_design_clk_dvdr_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_clk_dvdr_2_0 || ORIG_REF_NAME==main_design_clk_dvdr_2_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_enable_0_0/main_design_enable_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_enable_0_0 || ORIG_REF_NAME==main_design_enable_0_0} -quiet] -quiet

# XDC: /home/rootuser/Desktop/Vivado/rgb_clk_dvdr/rgb_clk_dvdr.gen/sources_1/bd/main_design/main_design_ooc.xdc
